### ISSUE TITLE
A couple of newbie issues

### ISSUE THREAD

**Issue by spectromas** [agraef/midizap#1]
I'm using a Novation Launchcontrol XL and I would like to change the colours of the buttons. According to the [programmer's reference](https://d2xhy469pqj8rc.cloudfront.net/sites/default/files/novation/downloads/9922/launch-control-xl-programmers-reference-guide.pdf) this (I think) can be achieved by using velocity. I'm not sure where in the documentation it explains how to send note velocity but I saw in the APCMini example that it is being used like this: 
```
# rec: color = red (vel. 3)
C0  C0[3]
```
However, if I use this [ ] format in the same way, with the values stated in the above guide, I get no feedback at all (without [ ]  I get yellow feedback). Do you have any idea how I can make this work? 

Also, I am using VCV Rack so I have MIDI-CAT receiving from midizap and feeding back to midizap on midi2 and this works, I get feedback on the buttons, but sending back to midizap causes the faders and knobs to act strangely and they don't move correctly as if there is something fighting with the movement. I don't have anything for them in [MIDI2] as they are not motorized but it seems there is some interference when sending feedback from VCV Rack to midizap.

**Comment by agraef** [comment]
Well, if I read the table on page 4 of the manual correctly, the correct velocity value to get a full red light would be 15 (3+12), not 3.

As for the VCV Rack feedback issue, it's impossible to say what's going on there without the midizaprc file and the exact configuration of the MIDI Jack connections from and to midizap that you're using. You could try to debug the issue using midizap's debugging options (e.g., `-drk` or `-drkm` are usually most useful) and observing the translations executed by midizap.

But if you don't have any translations in the [MIDI2] section and you're not using any of the passthrough options then I don't think that there's a way that those MIDI messages could mess with the internal state of your Launchcontrol. It's more likely that they mess up midizap's internal state regarding the forward translations. If you post the forward translations for the knobs and sliders then I *might* be able to say more. Not sure whether I'll be able to help, though, it's often hard to diagnose such issues without having the actual hardware available.

**Comment by spectromas** [comment]
The velocity doesn't seem to make any difference unfortunately except for disabling feedback on that parameter. 

It seems I'm getting high and low values when trying to move one of the faders: 

```
[1] CC77-1 value = 46
[0] CC77-1 value = 80
CC77-1+: CC77-1 
[1] CC77-1 value = 52
[0] CC77-1 value = 81
CC77-1+: CC77-1 
[1] CC77-1 value = 55
[0] CC77-1 value = 82
CC77-1+: CC77-1 
[1] CC77-1 value = 52
```

Here is my config, is there anything obvious? 
[midizaprc_launchcontrol.zip](https://github.com/agraef/midizap/files/5418702/midizaprc_launchcontrol.zip)

These are the connections, fairly simple. 
![Screenshot_20201021_220014](https://user-images.githubusercontent.com/6443372/96786942-ddd50e00-13e8-11eb-9504-171e01e9b97a.png)

**Comment by agraef** [comment]
The connections are looking good.

> The velocity doesn't seem to make any difference unfortunately except for disabling feedback on that parameter.

Well, it was worth a try. ;-) I'm afraid that I just don't know anything about the LaunchControl. It seems that it can be run in different modes and/or with different templates, so it's possible that it's configured in a different way than what is described in the manual. Your best bet is to have a look in the editor, or, if that doesn't help either, just give it the good old college try and  experiment with different values.

About the fader values, it looks like the internal states of midizap and VCV Rack aren't in sync. That's a common problem when using the incremental translations if you don't have motor faders or encoders. Try a basic mod translation like this instead:

~~~
CC77[]   CC77
~~~

That will transfer absolute values instead of incremental value changes, which will hopefully get rid of the issue. If that doesn't do the trick then you can try to disable the unwanted feedback by using a rule like the following in the [MIDI2] section:

~~~
CC77=   NOP
~~~

If that doesn't help either, then I'm out of ideas, sorry. :(

**Comment by spectromas** [comment]
Using [] works for the faders and knobs, thank you! 

I realised what I was doing wrong for the colour feedback. I was using `F3-1 F3-1[15]` but if I take out the -1 then it works as expected. 

Thank you so much for your help and for your work on making this program, it's incredible!

**Comment by agraef** [comment]
Looking at the grammar at the end of the midizap manpage, I think that `F3[15]-1` is the proper syntax:

~~~bnf
midi-token  ::= msg [ mod ] [ steps ] [ "-" number] [ flag ]
~~~

**Comment by agraef** [comment]
BTW, if you got your setup in good shape now, maybe you could just add a few comments with your copyright and a brief description of how it's supposed to be used in conjunction with VCV Rack, and submit it so that I can add it to the examples? I'm always interested in configs that might be useful for others. :wink: And we don't have an example for VCV Rack yet, most of the existing examples are just Mackie emulations.

**Comment by spectromas** [comment]
Absolutely, I would be happy to share it. So far I haven't done anything particularly interesting or advanced with midizap, I'm sure I'm only scratching the surface, but it may save someone else some time figuring out the same thing. I think it might be helpful if I also include the Rack template file as some of the config choices only really make sense when they are mapped, is that something you would be able to include as well?

**Comment by agraef** [comment]
> I think it might be helpful if I also include the Rack template file as some of the config choices only really make sense when they are mapped, is that something you would be able to include as well?

Yes, sure!
